## -*- texinfo -*-
## @deftypefn  {} {} dummy()
##
## This is a dummy function documentation. This file have a lot functions
## and each one have a little documentation. This text is to avoid a warning when
## install this file as part of package.
## @end deftypefn
##
## Set the graphics toolkit and force read this file as script file (not a function file).
##
graphics_toolkit qt;
##


##
##
## Begin callbacks definitions 
##

## @deftypefn  {} {} btn_closeCDCsimulpaameters_doIt (@var{source}, @var{callbackdata}, @var{cdCSimParamWnd})
##
## Define a callback for default action of btn_closeCDCsimulpaameters control.
##
## @end deftypefn
function btn_closeCDCsimulpaameters_doIt(source, callbackdata, cdCSimParamWnd)

% global variable
global _ltitoolBasePath;

% I get the data from the window
amplitud_sp = eval(get(cdCSimParamWnd.amplitud_sp, 'string'));
T_sp = eval(get(cdCSimParamWnd.T_sp, 'string'));
amplitud_l1 = eval(get(cdCSimParamWnd.amplitud_l1, 'string'));
amplitud_l2 = eval(get(cdCSimParamWnd.amplitud_l2, 'string'));
T_l1 = eval(get(cdCSimParamWnd.T_l1, 'string'));
T_l2 = eval(get(cdCSimParamWnd.T_l2, 'string'));
TFinal = eval(get(cdCSimParamWnd.TFinal, 'string'));
haChCarga1 = get(cdCSimParamWnd.Load_changeL1, 'value');
haChCarga2 = get(cdCSimParamWnd.Load_changeL2, 'value');
haChCons = get(cdCSimParamWnd.SP_change, 'value');

% Save data
save([_ltitoolBasePath filesep() 'data' filesep() 'loadCDCsim'],'T_sp','T_l1','T_l2','TFinal', ...
                                           'amplitud_sp','amplitud_l1','amplitud_l2', ...
                                           'haChCons','haChCarga1','haChCarga2');

% Close window
close(cdCSimParamWnd.figure);

end

 
## @deftypefn  {} {@var{ret} = } show_cdCSimParamWnd()
##
## Create windows controls over a figure, link controls with callbacks and return 
## a window struct representation.
##
## @end deftypefn
function ret = show_cdCSimParamWnd()
  _scrSize = get(0, "screensize");
  _xPos = (_scrSize(3) - 685)/2;
  _yPos = (_scrSize(4) - 343)/2;
   cdCSimParamWnd = figure ( ... 
	'Color', [0.961 0.965 0.969], ...
	'Position', [_xPos _yPos 685 343], ...
	'Resize', 'on', ...
	'windowstyle', 'normal', ...
	'MenuBar', 'none');
  Label_20 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [208 308 299 20], ... 
	'String', 'Simutation Parameters', ... 
	'TooltipString', '');
  k_sp = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [20 211 145 17], ... 
	'String', 'SP Step Amplitude', ... 
	'TooltipString', '');
  k_l = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [265 211 157 17], ... 
	'String', 'Load Step Amplitudes', ... 
	'TooltipString', '');
  amplitud_sp = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [170 209 54 22], ... 
	'String', '', ... 
	'TooltipString', '');
  amplitud_l1 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [425 209 49 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Label_25 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [20 173 106 17], ... 
	'String', 'Input Time', ... 
	'TooltipString', '');
  Label_26 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [265 173 127 17], ... 
	'String', 'Input Time', ... 
	'TooltipString', '');
  T_sp = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [170 171 46 22], ... 
	'String', '', ... 
	'TooltipString', '');
  T_l1 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [426 171 48 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Label_27 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [20 111 142 17], ... 
	'String', 'Simulation', ... 
	'TooltipString', '');
  Label_28 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [20 68 132 17], ... 
	'String', 'Simulation Time', ... 
	'TooltipString', '');
  TFinal = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [165 66 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  btn_closeCDCsimulpaameters = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [579 11 90 22], ... 
	'String', 'OK', ... 
	'TooltipString', '');
  SP_change = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [20 251 193 17], ... 
	'String', 'Set-Point Change', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  Load_changeL1 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [260 251 189 17], ... 
	'String', 'Load Change (L1)', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  Load_changeL2 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [500 251 184 17], ... 
	'String', 'Load Change  (L2)', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  amplitud_l2 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [539 209 50 22], ... 
	'String', '', ... 
	'TooltipString', '');
  T_l2 = uicontrol( ...
	'parent',cdCSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [540 171 46 22], ... 
	'String', '', ... 
	'TooltipString', '');

  cdCSimParamWnd = struct( ...
      'figure', cdCSimParamWnd, ...
      'Label_20', Label_20, ...
      'k_sp', k_sp, ...
      'k_l', k_l, ...
      'amplitud_sp', amplitud_sp, ...
      'amplitud_l1', amplitud_l1, ...
      'Label_25', Label_25, ...
      'Label_26', Label_26, ...
      'T_sp', T_sp, ...
      'T_l1', T_l1, ...
      'Label_27', Label_27, ...
      'Label_28', Label_28, ...
      'TFinal', TFinal, ...
      'btn_closeCDCsimulpaameters', btn_closeCDCsimulpaameters, ...
      'SP_change', SP_change, ...
      'Load_changeL1', Load_changeL1, ...
      'Load_changeL2', Load_changeL2, ...
      'amplitud_l2', amplitud_l2, ...
      'T_l2', T_l2);


  set (btn_closeCDCsimulpaameters, 'callback', {@btn_closeCDCsimulpaameters_doIt, cdCSimParamWnd});
  dlg = struct(cdCSimParamWnd);

% global variable
global _ltitoolBasePath;

%  Load data
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCDCsim']) 

% Show data on window
set(cdCSimParamWnd.amplitud_sp,'string',num2str(amplitud_sp));
set(cdCSimParamWnd.T_sp,'string',num2str(T_sp));
set(cdCSimParamWnd.amplitud_l1,'string',num2str(amplitud_l1));
set(cdCSimParamWnd.amplitud_l2,'string',num2str(amplitud_l2));
set(cdCSimParamWnd.T_l1,'string',num2str(T_l1));
set(cdCSimParamWnd.T_l2,'string',num2str(T_l2));
set(cdCSimParamWnd.TFinal,'string',num2str(TFinal));
set(cdCSimParamWnd.Load_changeL1, 'value', haChCarga1);
set(cdCSimParamWnd.Load_changeL2, 'value', haChCarga2);
set(cdCSimParamWnd.SP_change, 'value', haChCons);


  ret = cdCSimParamWnd;
end

