## -*- texinfo -*-
## @deftypefn  {} {} dummy()
##
## This is a dummy function documentation. This file have a lot functions
## and each one have a little documentation. This text is to avoid a warning when
## install this file as part of package.
## @end deftypefn
##
## Set the graphics toolkit and force read this file as script file (not a function file).
##
graphics_toolkit qt;
##


##
##
## Begin callbacks definitions 
##

## @deftypefn  {} {} btn_closeCLanalysis_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_closeCLanalysis control.
##
## @end deftypefn
function btn_closeCLanalysis_doIt(source, callbackdata, cLAnalysisWnd)


% Close window
close(cLAnalysisWnd.figure);

end

## @deftypefn  {} {} btn_rlocus_CL_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_rlocus_CL control.
##
## @end deftypefn
function btn_rlocus_CL_doIt(source, callbackdata, cLAnalysisWnd)

%
% Plot root locus
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

% Plot root locus
% ----------------------------------
axes(cLAnalysisWnd.ImageLR);
[Kast,Kast_ult,wultimo,GM,wcg,PM]=GHrlocusplot(GH.num{1,1},GH.den{1,1},Kr,1000);
hold off

end

## @deftypefn  {} {} btn_Bode_CL_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_Bode_CL control.
##
## @end deftypefn
function btn_Bode_CL_doIt(source, callbackdata, cLAnalysisWnd)


%
% Plot Bode diagrams
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

% Plot Bode diagrams
% ----------------------------------
axes(cLAnalysisWnd.ImageBodeMag);
delay=0;
flagMagPha='gragicoMag';
[Kast,Kast_ult,wultimo,GM,wcg,PM]=bodeplotMagPha(GH.num{1,1},GH.den{1,1},delay,Kr,flagMagPha);
hold off
axes(cLAnalysisWnd.ImageBodePha);
flagMagPha='gragicoPha';
[Kast,Kast_ult,wultimo,GM,wcg,PM]=bodeplotMagPha(GH.num{1,1},GH.den{1,1},delay,Kr,flagMagPha);
hold off

end

## @deftypefn  {} {} btn_Nyquist_CL_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_Nyquist_CL control.
##
## @end deftypefn
function btn_Nyquist_CL_doIt(source, callbackdata, cLAnalysisWnd)


%
% Plot Nyquist diagram
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

% Plot Nyquist diagram
% ----------------------------------
axes(cLAnalysisWnd.ImageNyq);
delay=0;
[Kast,Kast_ult,wultimo,GM,wcg,PM]=GHnyquistplot(GH.num{1,1},GH.den{1,1},delay,Kr);
hold off

end

## @deftypefn  {} {} btn_GHmap_CL_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_GHmap_CL control.
##
## @end deftypefn
function btn_GHmap_CL_doIt(source, callbackdata, cLAnalysisWnd)

%
% Plot zeros-poles map of open loop transfer function (GH)
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

% ------------------------------------------------------------------------------------
% Zeros-Poles map of G(s)H(s)
title_string='Poles-Zeros Map of G(s)H(s)';
legend_ceros_string='Zeros of G(s)H(s)';
legend_polos_string='Poles of G(s)H(s)';

% Plot zeros-poles map
% ----------------------------------
axes(cLAnalysisWnd.ImageZPGH);
xpzmap(title_string,legend_ceros_string,legend_polos_string,GH.num{1,1},GH.den{1,1});
figuraGH=1;
% ------------------------------------------------------------------------------------

end

## @deftypefn  {} {} btn_Gclmap_CL_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_Gclmap_CL control.
##
## @end deftypefn
function btn_Gclmap_CL_doIt(source, callbackdata, cLAnalysisWnd)

%
% Plot zeros-poles map of  closed loop system,  Gcl(s)
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

%Closed loop transfer function (Gcl)
Gcl = minreal(GH/(1+GH));

% -------------------------------------------------------------------------
% Poles-Zeros map of closed loop system
title_string='Poles-Zeros Map of Gcls)';
legend_ceros_string='Zeros of Gcl(s)';
legend_polos_string='Poles of Gcl(s)';

% Plot zeros-poles map
% ----------------------------------
axes(cLAnalysisWnd.ImageZPGLC);
xpzmap(title_string,legend_ceros_string,legend_polos_string,Gcl.num{1,1},Gcl.den{1,1});
figuraGH=2;
% -------------------------------------------------------------------------

%
refresh();

end

## @deftypefn  {} {} btn_rlocusplus_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_rlocusplus control.
##
## @end deftypefn
function btn_rlocusplus_doIt(source, callbackdata, cLAnalysisWnd)


%
% Llama a graficar el lugar de las raices
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

% Presento grafico
% ----------------------------------
figure
delay=0;
[Kast,Kast_ult,wultimo,GM,wcg,PM]=GHrlocusplot(GH.num{1,1},GH.den{1,1},Kr,1000);
axisx=xlabel('Real G(s)H(s)'); axisy=ylabel('Imag. G(s)H(s)');
set(axisx,'fontsize',14);  
set(axisy,'fontsize',14);

end

## @deftypefn  {} {} btn_Bodeplus_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_Bodeplus control.
##
## @end deftypefn
function btn_Bodeplus_doIt(source, callbackdata, cLAnalysisWnd)


%
% Llama a graficar elos diagramas de Bode
%

% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])

% Presento grafico
% ----------------------------------
figure();
delay=0;
[Kast,Kast_ult,wultimo,GM,wcg,PM]=GHbodeplot(GH.num{1,1},GH.den{1,1},delay,Kr);
 

end

## @deftypefn  {} {} btn_Nyqplus_doIt (@var{source}, @var{callbackdata}, @var{cLAnalysisWnd})
##
## Define a callback for default action of btn_Nyqplus control.
##
## @end deftypefn
function btn_Nyqplus_doIt(source, callbackdata, cLAnalysisWnd)


%
% Llama a graficar el diagrama de Nyquist
%


% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])


% Presento grafico
% ----------------------------------
figure
delay=0;
[Kast,Kast_ult,wultimo,GM,wcg,PM]=GHnyquistplot(GH.num{1,1},GH.den{1,1},delay,Kr);

end

 
## @deftypefn  {} {@var{ret} = } show_cLAnalysisWnd()
##
## Create windows controls over a figure, link controls with callbacks and return 
## a window struct representation.
##
## @end deftypefn
function ret = show_cLAnalysisWnd()
  _scrSize = get(0, "screensize");
  _xPos = (_scrSize(3) - 1189)/2;
  _yPos = (_scrSize(4) - 673)/2;
   cLAnalysisWnd = figure ( ... 
	'Color', [0.961 0.965 0.969], ...
	'Position', [_xPos _yPos 1189 673], ...
	'Resize', 'on', ...
	'windowstyle', 'normal', ...
	'MenuBar', 'none');
  GCLanalysis = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [400 621 395 42], ... 
	'String', 'Analysis Tools for Feedback Systems', ... 
	'TooltipString', '');
  btn_closeCLanalysis = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [1067 16 90 22], ... 
	'String', 'Close', ... 
	'TooltipString', '');
  btn_rlocus_CL = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [40 365 137 23], ... 
	'String', 'Root Locus', ... 
	'TooltipString', '');
  btn_Bode_CL = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [420 365 137 23], ... 
	'String', 'Bode', ... 
	'TooltipString', '');
  btn_Nyquist_CL = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [810 365 136 23], ... 
	'String', 'Nyquist', ... 
	'TooltipString', '');
  Label_2 = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [40 401 230 17], ... 
	'String', 'Analysis Based on G(s)H(s)', ... 
	'TooltipString', '');
  Label_3 = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [40 561 166 17], ... 
	'String', 'Poles-Zeros Map', ... 
	'TooltipString', '');
  btn_GHmap_CL = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [40 521 243 22], ... 
	'String', 'Poles-Zeros of G(s)H(s)', ... 
	'TooltipString', '');
  btn_Gclmap_CL = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [40 481 239 22], ... 
	'String', 'Poles-Zeros of Closed Loop', ... 
	'TooltipString', '');
  ImageZPGH = axes( ...
	'Units', 'pixels', ... 
	'parent',cLAnalysisWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [425 436 301 144]);
  ImageLR = axes( ...
	'Units', 'pixels', ... 
	'parent',cLAnalysisWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [40 64 298 259]);
  ImageBodeMag = axes( ...
	'Units', 'pixels', ... 
	'parent',cLAnalysisWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [425 229 305 94]);
  ImageBodePha = axes( ...
	'Units', 'pixels', ... 
	'parent',cLAnalysisWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [425 66 304 92]);
  ImageNyq = axes( ...
	'Units', 'pixels', ... 
	'parent',cLAnalysisWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [810 63 305 260]);
  btn_rlocusplus = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [340 306 42 22], ... 
	'String', '+', ... 
	'TooltipString', '');
  btn_Bodeplus = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [730 306 43 22], ... 
	'String', '+', ... 
	'TooltipString', '');
  btn_Nyqplus = uicontrol( ...
	'parent',cLAnalysisWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [1115 306 42 22], ... 
	'String', '+', ... 
	'TooltipString', '');
  ImageZPGLC = axes( ...
	'Units', 'pixels', ... 
	'parent',cLAnalysisWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [815 434 302 149]);

  cLAnalysisWnd = struct( ...
      'figure', cLAnalysisWnd, ...
      'GCLanalysis', GCLanalysis, ...
      'btn_closeCLanalysis', btn_closeCLanalysis, ...
      'btn_rlocus_CL', btn_rlocus_CL, ...
      'btn_Bode_CL', btn_Bode_CL, ...
      'btn_Nyquist_CL', btn_Nyquist_CL, ...
      'Label_2', Label_2, ...
      'Label_3', Label_3, ...
      'btn_GHmap_CL', btn_GHmap_CL, ...
      'btn_Gclmap_CL', btn_Gclmap_CL, ...
      'ImageZPGH', ImageZPGH, ...
      'ImageLR', ImageLR, ...
      'ImageBodeMag', ImageBodeMag, ...
      'ImageBodePha', ImageBodePha, ...
      'ImageNyq', ImageNyq, ...
      'btn_rlocusplus', btn_rlocusplus, ...
      'btn_Bodeplus', btn_Bodeplus, ...
      'btn_Nyqplus', btn_Nyqplus, ...
      'ImageZPGLC', ImageZPGLC);


  set (btn_closeCLanalysis, 'callback', {@btn_closeCLanalysis_doIt, cLAnalysisWnd});
  set (btn_rlocus_CL, 'callback', {@btn_rlocus_CL_doIt, cLAnalysisWnd});
  set (btn_Bode_CL, 'callback', {@btn_Bode_CL_doIt, cLAnalysisWnd});
  set (btn_Nyquist_CL, 'callback', {@btn_Nyquist_CL_doIt, cLAnalysisWnd});
  set (btn_GHmap_CL, 'callback', {@btn_GHmap_CL_doIt, cLAnalysisWnd});
  set (btn_Gclmap_CL, 'callback', {@btn_Gclmap_CL_doIt, cLAnalysisWnd});
  set (btn_rlocusplus, 'callback', {@btn_rlocusplus_doIt, cLAnalysisWnd});
  set (btn_Bodeplus, 'callback', {@btn_Bodeplus_doIt, cLAnalysisWnd});
  set (btn_Nyqplus, 'callback', {@btn_Nyqplus_doIt, cLAnalysisWnd});
  dlg = struct(cLAnalysisWnd);



% global variable
global _ltitoolBasePath;

%
% Load predefined data
% --------------------------------
load([_ltitoolBasePath filesep() 'data' filesep() 'loadCLdata'])


  ret = cLAnalysisWnd;
end

