## -*- texinfo -*-
## @deftypefn  {} {} dummy()
##
## This is a dummy function documentation. This file have a lot functions
## and each one have a little documentation. This text is to avoid a warning when
## install this file as part of package.
## @end deftypefn
##
## Set the graphics toolkit and force read this file as script file (not a function file).
##
graphics_toolkit qt;
##


##
##
## Begin callbacks definitions 
##

## @deftypefn  {} {} btn_closeFFsimulpaameters_doIt (@var{source}, @var{callbackdata}, @var{ffSimParamWnd})
##
## Define a callback for default action of btn_closeFFsimulpaameters control.
##
## @end deftypefn
function btn_closeFFsimulpaameters_doIt(source, callbackdata, ffSimParamWnd)

% global variable
global _ltitoolBasePath;

% I get the data from the window
amplitud_sp = eval(get(ffSimParamWnd.amplitud_sp, 'string'));
T_sp = eval(get(ffSimParamWnd.T_sp, 'string'));
amplitud_l = eval(get(ffSimParamWnd.amplitud_l, 'string'));
T_l = eval(get(ffSimParamWnd.T_l, 'string'));
TFinal = eval(get(ffSimParamWnd.TFinal, 'string'));
haChCarga = get(ffSimParamWnd.Load_change, 'value');
haChCons = get(ffSimParamWnd.SP_change, 'value');

% Save data
save([_ltitoolBasePath filesep() 'data' filesep() 'loadFFsim'],'T_sp','T_l','TFinal','amplitud_sp','amplitud_l', ...
                                           'haChCons', 'haChCarga')      

% Close window
close(ffSimParamWnd.figure);

end

 
## @deftypefn  {} {@var{ret} = } show_ffSimParamWnd()
##
## Create windows controls over a figure, link controls with callbacks and return 
## a window struct representation.
##
## @end deftypefn
function ret = show_ffSimParamWnd()
  _scrSize = get(0, "screensize");
  _xPos = (_scrSize(3) - 545)/2;
  _yPos = (_scrSize(4) - 349)/2;
   ffSimParamWnd = figure ( ... 
	'Color', [0.961 0.965 0.969], ...
	'Position', [_xPos _yPos 545 349], ...
	'Resize', 'on', ...
	'windowstyle', 'normal', ...
	'MenuBar', 'none');
  Label_20 = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [170 304 274 20], ... 
	'String', 'Simutation Parameters', ... 
	'TooltipString', '');
  k_sp = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [30 219 108 15], ... 
	'String', 'SP Step Amplitude', ... 
	'TooltipString', '');
  k_l = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [295 217 138 17], ... 
	'String', 'Load Step Amplitude', ... 
	'TooltipString', '');
  amplitud_sp = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [175 215 54 22], ... 
	'String', '', ... 
	'TooltipString', '');
  amplitud_l = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [440 215 49 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Label_25 = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [30 181 61 15], ... 
	'String', 'Input Time', ... 
	'TooltipString', '');
  Label_26 = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [295 179 105 17], ... 
	'String', 'Input Time', ... 
	'TooltipString', '');
  T_sp = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [175 177 54 22], ... 
	'String', '', ... 
	'TooltipString', '');
  T_l = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [441 177 48 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Label_27 = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [30 117 135 17], ... 
	'String', 'Simulation', ... 
	'TooltipString', '');
  Label_28 = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [30 82 133 17], ... 
	'String', 'Simulation Time', ... 
	'TooltipString', '');
  TFinal = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [175 82 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  btn_closeFFsimulpaameters = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [439 22 90 22], ... 
	'String', 'OK', ... 
	'TooltipString', '');
  SP_change = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [30 252 194 17], ... 
	'String', 'Set-Point Change', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  Load_change = uicontrol( ...
	'parent',ffSimParamWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.961 0.965 0.969], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [295 252 174 17], ... 
	'String', 'Load Change', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);

  ffSimParamWnd = struct( ...
      'figure', ffSimParamWnd, ...
      'Label_20', Label_20, ...
      'k_sp', k_sp, ...
      'k_l', k_l, ...
      'amplitud_sp', amplitud_sp, ...
      'amplitud_l', amplitud_l, ...
      'Label_25', Label_25, ...
      'Label_26', Label_26, ...
      'T_sp', T_sp, ...
      'T_l', T_l, ...
      'Label_27', Label_27, ...
      'Label_28', Label_28, ...
      'TFinal', TFinal, ...
      'btn_closeFFsimulpaameters', btn_closeFFsimulpaameters, ...
      'SP_change', SP_change, ...
      'Load_change', Load_change);


  set (btn_closeFFsimulpaameters, 'callback', {@btn_closeFFsimulpaameters_doIt, ffSimParamWnd});
  dlg = struct(ffSimParamWnd);

% global variable
global _ltitoolBasePath;

%  Load data
load([_ltitoolBasePath filesep() 'data' filesep() 'loadFFsim'])

% Show data on window
set(ffSimParamWnd.amplitud_sp,'string',num2str(amplitud_sp));
set(ffSimParamWnd.T_sp,'string',num2str(T_sp));
set(ffSimParamWnd.amplitud_l,'string',num2str(amplitud_l));
set(ffSimParamWnd.T_l,'string',num2str(T_l));
set(ffSimParamWnd.TFinal,'string',num2str(TFinal));
set(ffSimParamWnd.Load_change, 'value', haChCarga);
set(ffSimParamWnd.SP_change, 'value', haChCons);

  ret = ffSimParamWnd;
end

