## -*- texinfo -*-
## @deftypefn  {} {} dummy()
##
## This is a dummy function documentation. This file have a lot functions
## and each one have a little documentation. This text is to avoid a warning when
## install this file as part of package.
## @end deftypefn
##
## Set the graphics toolkit and force read this file as script file (not a function file).
##
graphics_toolkit qt;
##


##
##
## Begin callbacks definitions 
##

## @deftypefn  {} {} btn_closeOptimalPID_doIt (@var{source}, @var{callbackdata}, @var{optimalPIDWnd})
##
## Define a callback for default action of btn_closeOptimalPID control.
##
## @end deftypefn
function btn_closeOptimalPID_doIt(source, callbackdata, optimalPIDWnd)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% propertie 'have callback' from the properties editor

% Close Optimal PID windown
close(optimalPIDWnd.figure);

end

## @deftypefn  {} {} btn_help_optm_doIt (@var{source}, @var{callbackdata}, @var{optimalPIDWnd})
##
## Define a callback for default action of btn_help_optm control.
##
## @end deftypefn
function btn_help_optm_doIt(source, callbackdata, optimalPIDWnd)


%
% Run presentation to help  as html file.
%

% global variable
global _ltitoolBasePath;

% Load html file
url = ["file:" _ltitoolBasePath filesep() "ltitool_manual" filesep() "node26.html"];

  if(isunix())
    system(["xdg-open " url]);
  elseif (ispc())
    system(["start " url]);
  else
    disp(["I don't know how to open " url " in your os. Sorry!"]);
  endif;

end

## @deftypefn  {} {} btn_runOPTMPID_doIt (@var{source}, @var{callbackdata}, @var{optimalPIDWnd})
##
## Define a callback for default action of btn_runOPTMPID control.
##
## @end deftypefn
function btn_runOPTMPID_doIt(source, callbackdata, optimalPIDWnd)


%
% Load default values for optimal PID window
%

% global variable
global _ltitoolBasePath;

%------------------------------------------------------------------------------------------------
% Data from main window
% Complex variable "s"
s = tf('s');
% Built Gp(s) transfer function
numGp = get(optimalPIDWnd.numGp, 'string');
denGp = get(optimalPIDWnd.denGp, 'string');
sysStrGH = strcat('(',numGp,')', '/','(', denGp,')');
Gp = minreal(tf(eval(sysStrGH)));

% Proposed controller
Kr = str2num(get(optimalPIDWnd.Kr, 'string'));
TI = str2num(get(optimalPIDWnd.TI, 'string'));
TD = str2num(get(optimalPIDWnd.TD, 'string'));
% Function weight
wITAE = str2num(get(optimalPIDWnd.wITAE, 'string'));
wOVS = str2num(get(optimalPIDWnd.wOVS, 'string'));
wS = str2num(get(optimalPIDWnd.wS, 'string'));
%------------------------------------------------------------------------------------------------


% PROVISORIO !!!!!
Ts=0.1; tFinal=30

% Global Variables
global P dt mu_1 mu_2 mu_3
P=Gp; mu_1=wITAE; mu_2=wOVS; mu_3=wS; dt=Ts;

% Run optimization routine
scrSize = get(0, "screensize");
xPos = (scrSize(3) - 180)/2;
yPos = (scrSize(4) - 70)/2;
wh = waitbar(0.3, 'Please be patient', 'Position',[xPos yPos 180 70]);
[Kropt,TIopt, TDopt]=xoptiPID(Kr,TI,TD,Gp,tFinal,Ts,wITAE,wOVS,wS);
close(wh); % Close calculating window

% ------------------------------------------------------------------------
% Reload information to main window
% ------------------------------------------------------------------------
set(optimalPIDWnd.Kropt,'string',num2str(Kropt));
set(optimalPIDWnd.TIopt,'string',num2str(TIopt));
set(optimalPIDWnd.TDopt,'string',num2str(TDopt));
% ------------------------------------------------------------------------
end

## @deftypefn  {} {} btn_setdefaultOPTMPID_doIt (@var{source}, @var{callbackdata}, @var{optimalPIDWnd})
##
## Define a callback for default action of btn_setdefaultOPTMPID control.
##
## @end deftypefn
function btn_setdefaultOPTMPID_doIt(source, callbackdata, optimalPIDWnd)


%
% Load default values for optimal PID window
%
%

% global variable
global _ltitoolBasePath;

% Complex variable "s"
s=tf('s'); 

% Transfer function
% --------------------------
Gp=10/(s^3+6*s^2+11*s+6);

% Controllers
% Proposed controller
Kr=1.00000; TI=1.00000; TD=0.00000;
% Optimal controller
Kropt=1; TIopt=1; TDopt=0;

% Simulation data
Ts=0.1;     %sample time
tFinal=10;  %simulation time

% Function weight
wITAE=1;
wOVS=10;
wS=20;

% Save default data
% ---------------------------
save([_ltitoolBasePath filesep() 'data' filesep() 'loadOPTMPIDdata'],'Gp','Kr','TI','TD', ...
                          'Kropt','TIopt','TDopt','Ts','tFinal','wITAE','wOVS','wS')

% ------------------------------------------------------------------------
% Reload information to main window
% ------------------------------------------------------------------------
set(optimalPIDWnd.numGp,'string',polyout(Gp.num{1,1})); 
set(optimalPIDWnd.denGp,'string',polyout(Gp.den{1,1}));
set(optimalPIDWnd.Kr,'string',num2str(Kr));
set(optimalPIDWnd.TI,'string',num2str(TI));
set(optimalPIDWnd.TD,'string',num2str(TD));
set(optimalPIDWnd.Kropt,'string',num2str(Kropt));
set(optimalPIDWnd.TIopt,'string',num2str(TIopt));
set(optimalPIDWnd.TDopt,'string',num2str(TDopt));
set(optimalPIDWnd.wITAE,'string',num2str(wITAE));
set(optimalPIDWnd.wOVS,'string',num2str(wOVS));
set(optimalPIDWnd.wS,'string',num2str(wS));
% ------------------------------------------------------------------------

end

 
## @deftypefn  {} {@var{ret} = } show_optimalPIDWnd()
##
## Create windows controls over a figure, link controls with callbacks and return 
## a window struct representation.
##
## @end deftypefn
function ret = show_optimalPIDWnd()
  _scrSize = get(0, "screensize");
  _xPos = (_scrSize(3) - 840)/2;
  _yPos = (_scrSize(4) - 595)/2;
   optimalPIDWnd = figure ( ... 
	'Color', [0.937 0.922 0.906], ...
	'Position', [_xPos _yPos 840 595], ...
	'Resize', 'on', ...
	'windowstyle', 'normal', ...
	'MenuBar', 'none');
  btn_closeOptimalPID = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [726 13 90 22], ... 
	'String', 'Close', ... 
	'TooltipString', '');
  Label_189 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 15, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [273 550 556 35], ... 
	'String', 'Optimal PID Controller Tuning', ... 
	'TooltipString', '');
  Label_190 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [425 458 307 17], ... 
	'String', 'G(s) = ----------------------------------------------', ... 
	'TooltipString', '');
  Label_191 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [420 528 76 17], ... 
	'String', 'Plant:', ... 
	'TooltipString', '');
  numGp = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [475 478 190 22], ... 
	'String', '', ... 
	'TooltipString', '');
  denGp = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [470 428 197 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Label_192 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [10 383 601 17], ... 
	'String', 'Adopt the parameters of a PID controller and enter its modes', ... 
	'TooltipString', '');
  PID_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [10 355 250 15], ... 
	'String', 'C(s)=Kr(1+1/TIs+TDs)', ... 
	'TooltipString', '');
  Mode_P = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [5 303 77 17], ... 
	'String', 'P Mode', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  TI = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [205 303 74 17], ... 
	'String', 'I Mode', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  Mode_D = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [400 303 80 17], ... 
	'String', 'D Mode', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1);
  Kr = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [95 301 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  TI = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [285 301 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  TD = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [490 301 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Label_194 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [5 263 681 17], ... 
	'String', 'The optimal controller calculation strongly depends on the initial conditions.', ... 
	'TooltipString', '');
  Label_195 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [5 243 684 17], ... 
	'String', 'Be sure to correctly initialize the chosen controller to determine its optimal parameters.', ... 
	'TooltipString', '');
  Label_196 = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [5 203 166 17], ... 
	'String', 'Weight Functions:', ... 
	'TooltipString', '');
  W_ITA_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [180 203 206 17], ... 
	'String', 'Minimize ITAE Criterion', ... 
	'TooltipString', '');
  wITAE = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [425 201 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  W_OVS_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [180 170 231 15], ... 
	'String', 'Minimize Maximum Overshoot', ... 
	'TooltipString', '');
  wOVS = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [425 166 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  W_S_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [180 130 236 15], ... 
	'String', 'Minimize Sensitivity Function', ... 
	'TooltipString', '');
  wS = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [425 126 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  Kr_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [113 48 26 17], ... 
	'String', 'Kr:', ... 
	'TooltipString', '');
  Kropt = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [150 46 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  TI_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [266 48 25 17], ... 
	'String', 'TI:', ... 
	'TooltipString', '');
  TIopt = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 46 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  TD_label = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [414 50 21 15], ... 
	'String', 'TD:', ... 
	'TooltipString', '');
  TDopt = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [455 46 90 22], ... 
	'String', '', ... 
	'TooltipString', '');
  btn_analysis_otpm = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [690 208 129 22], ... 
	'String', 'Analysis Tools', ... 
	'TooltipString', '');
  btn_sim_optm = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [690 168 125 22], ... 
	'String', 'Simulation', ... 
	'TooltipString', '');
  btn_help_optm = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [485 13 90 22], ... 
	'String', 'Help', ... 
	'TooltipString', '');
  btn_runOPTMPID = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [5 76 90 22], ... 
	'String', 'Optimal PID', ... 
	'TooltipString', '');
  btn_setdefaultOPTMPID = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [668 508 158 22], ... 
	'String', 'Load Default Values', ... 
	'TooltipString', '');
  optmPID_image = axes( ...
	'Units', 'pixels', ... 
	'parent',optimalPIDWnd, ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Ubuntu', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'Position', [15 412 395 133]);
  btn_saveOPTMPID = uicontrol( ...
	'parent',optimalPIDWnd, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.922 0.906], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Arial', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [605 13 90 22], ... 
	'String', 'Save', ... 
	'TooltipString', '');

  optimalPIDWnd = struct( ...
      'figure', optimalPIDWnd, ...
      'btn_closeOptimalPID', btn_closeOptimalPID, ...
      'Label_189', Label_189, ...
      'Label_190', Label_190, ...
      'Label_191', Label_191, ...
      'numGp', numGp, ...
      'denGp', denGp, ...
      'Label_192', Label_192, ...
      'PID_label', PID_label, ...
      'Mode_P', Mode_P, ...
      'TI', TI, ...
      'Mode_D', Mode_D, ...
      'Kr', Kr, ...
      'TI', TI, ...
      'TD', TD, ...
      'Label_194', Label_194, ...
      'Label_195', Label_195, ...
      'Label_196', Label_196, ...
      'W_ITA_label', W_ITA_label, ...
      'wITAE', wITAE, ...
      'W_OVS_label', W_OVS_label, ...
      'wOVS', wOVS, ...
      'W_S_label', W_S_label, ...
      'wS', wS, ...
      'Kr_label', Kr_label, ...
      'Kropt', Kropt, ...
      'TI_label', TI_label, ...
      'TIopt', TIopt, ...
      'TD_label', TD_label, ...
      'TDopt', TDopt, ...
      'btn_analysis_otpm', btn_analysis_otpm, ...
      'btn_sim_optm', btn_sim_optm, ...
      'btn_help_optm', btn_help_optm, ...
      'btn_runOPTMPID', btn_runOPTMPID, ...
      'btn_setdefaultOPTMPID', btn_setdefaultOPTMPID, ...
      'optmPID_image', optmPID_image, ...
      'btn_saveOPTMPID', btn_saveOPTMPID);


  set (btn_closeOptimalPID, 'callback', {@btn_closeOptimalPID_doIt, optimalPIDWnd});
  set (btn_help_optm, 'callback', {@btn_help_optm_doIt, optimalPIDWnd});
  set (btn_runOPTMPID, 'callback', {@btn_runOPTMPID_doIt, optimalPIDWnd});
  set (btn_setdefaultOPTMPID, 'callback', {@btn_setdefaultOPTMPID_doIt, optimalPIDWnd});
  dlg = struct(optimalPIDWnd);


%
% OTPIMAL PID CONTROLLER TUNING main window
%


% global variable
global _ltitoolBasePath;

%------------------------------------------------------------------------------------------------
% G(s)H(s) image
axes(optimalPIDWnd.optmPID_image);
imshow([_ltitoolBasePath filesep() 'img' filesep() 'figoptmPID.png']);
refresh();

%------------------------------------------------------------------------------------------------
% Load data defined by default
load([_ltitoolBasePath filesep() 'data' filesep() 'loadOPTMPIDdata'])
%------------------------------------------------------------------------------------------------

% Clear the command window
clc

%------------------------------------------------------------------------------------------------
% Show data inside teh window
set(optimalPIDWnd.numGp,'string',polyout(Gp.num{1,1})); 
set(optimalPIDWnd.denGp,'string',polyout(Gp.den{1,1}));
set(optimalPIDWnd.Kr,'string',num2str(Kr));
set(optimalPIDWnd.TI,'string',num2str(TI));
set(optimalPIDWnd.TD,'string',num2str(TD));
set(optimalPIDWnd.Kropt,'string',num2str(Kropt));
set(optimalPIDWnd.TIopt,'string',num2str(TIopt));
set(optimalPIDWnd.TDopt,'string',num2str(TDopt));
set(optimalPIDWnd.wITAE,'string',num2str(wITAE));
set(optimalPIDWnd.wOVS,'string',num2str(wOVS));
set(optimalPIDWnd.wS,'string',num2str(wS));
%------------------------------------------------------------------------------------------------



  ret = optimalPIDWnd;
end

